[profile.default]
src = "src"
out = "out"
libs = ["lib"]
remappings = [
    '@chainlink/contracts/=lib/chainlink-brownie-contracts/contracts/',
    '@openzeppelin/contracts=lib/openzeppelin-contracts/contracts',
    '@chainlink/contracts-ccip/=lib/ccip-contracts/contracts-ccip/',
]
fs_permissions = [{ access = "read", path = "./" }]
evm_version = "cancun"
solc = "0.8.25"

[etherscan]
polygon = { key = "${POLYGONSCAN_API_KEY}" }
sepolia = { key = "${ETHERSCAN_API_KEY}" }
mumbai = { key = "${POLYGONSCAN_API_KEY}" }

[rpc_endpoints]
polygon = "${POLYGON_RPC_URL}"
mumbai = "${MUMBAI_RPC_URL}"
sepolia = "${SEPOLIA_RPC_URL}"

[invariant]
runs = 64
depth = 64
fail_on_revert = true

[fmt]
bracket_spacing = true
int_types = "long"
line_length = 120
multiline_func_header = "all"
number_underscore = "thousands"
quote_style = "double"
tab_width = 4
wrap_comments = true

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
